version: '3.8'
services:
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    ports:
      - "7001:7001"
      - "17001:17001"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-conf/redis-node-1.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.28.0.2

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    ports:
      - "7002:7002"
      - "17002:17002"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-conf/redis-node-2.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.28.0.3

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    ports:
      - "7003:7003"
      - "17003:17003"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-conf/redis-node-3.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.28.0.4

  redis-node-4:
    image: redis:7.2
    container_name: redis-node-4
    ports:
      - "7004:7004"
      - "17004:17004"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-conf/redis-node-4.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.28.0.5

  redis-node-5:
    image: redis:7.2
    container_name: redis-node-5
    ports:
      - "7005:7005"
      - "17005:17005"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-conf/redis-node-5.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.28.0.6

  redis-node-6:
    image: redis:7.2
    container_name: redis-node-6
    ports:
      - "7006:7006"
      - "17006:17006"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-conf/redis-node-6.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.28.0.7

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
